#199
nbcp/leaderboard pull request #204
Opened 2020-11-09 14:02 UTC by allanalvarez

**Related github issue (required)**:

**Steps necessary to review your pull request (required)**:

2020-11-10 02:57 UTC, nbcp commented
@allanalvarez please do the ff: 
1. fill up the PR template (refer to previous PR's)
2. verify your commits (refer to our Teams' Wiki on how to do this)

2020-11-10 03:14 UTC, kaeleding commented
Hi @allanalvarez, in addition to Ben's comments, change the branch you want this to merge into from `master` to `staging`. Also keep the verified commits into a minimum (2-3), if it exceeds please squash the commits into one for review.

Thanks!

2021-01-22 08:12 UTC, nbcp requested changes

2021-01-28 02:20 UTC, allanalvarez commented on src/app/ui/join-team-page/join-team-page.component.ts
> +  }
I will be needing the undefined value for the Status column.
![image](https://user-images.githubusercontent.com/41406875/106080606-6256cb80-6152-11eb-87cc-bb613c6638ad.png)

2021-01-29 05:52 UTC, nbcp approved these changes

2021-01-29 06:18 UTC, emekld approved these changes

2021-01-29 06:22 UTC, edanga approved these changes

2021-01-29 06:26 UTC, merged